import Head from 'next/head';
import { JoinPage } from '../components/Join/Join';

export default function Join() {
  return (
    <section>
      <Head>
        <title>회원가입</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">회원가입</h1>
      <JoinPage />
    </section>
  );
}
